email: hello@particl.io
name: Particl
description: Particl is a private and censorship-resistant eCommerce platform built on blockchain and peer-to-peer technology.
keywords: "particl, part, blockchain, cryptocurrency"
baseurl: ""
url: "https://particl.io/"

donation-address: "$$$-donation-$$$-addy-$$$-here-$$$"

markdown: kramdown

# Kramdown was using smart quotes, which messes up CLI examples
# TODO: smart quotes are actually quite pretty, so this is perhaps better handled via a plugin that reverts them for CLI blocks
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
    input: GFM

exclude: ["README.md"]